### ISSUE TITLE
colored frame in comment dialogue

### ISSUE THREAD

**Issue by sanlifer** [Neovici/cosmoz-dialog-old#22]
![skarmavbild 2018-04-10 kl 14 19 17](https://user-images.githubusercontent.com/31737905/38556567-6865e5e2-3cca-11e8-9aff-2dead60eea80.png)
 
A blue line is displayed arounfd the input fields in the comment dialogue. See attached image.

When the input field is clicked, the frame disappears.

**Comment by nomego** [comment]
Fixed  @sanlifer ?
