### ISSUE TITLE
Backdrop covers/overlays the dialog when the element is used in a new stacking context

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-dialog-old#3]
If `<cosmoz-dialog>` is created inside another element within a new stacking context other than "root",  then the backdrop will cover the dialog.

The problem is also explained here https://github.com/PolymerElements/iron-overlay-behavior/issues/124#issuecomment-293351008

As described in this comment, the solution is to move the dialog content to a stacking context safe node.

The new `<iron-overlay>` element won't be available for Polymer 1,x, so we should try to do something similar for Polymer 1.x

**Comment by nomego** [comment]
Can we solve this? (by using cosmoz-dialog2 (rename?) or cosmoz-form-dialog?

**Comment by plequang** [comment]
Solved by implementing something similar to https://github.com/PolymerLabs/iron-overlay
